server:
  port: 8040
spring:
  application:
    name: microservice-gateway-zuul
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  # 忽略所有微服务时只路由指定的服务
  ignored-services: "*"
  user-route:
    strip-prefix: false
    service-id: microservice-comsumer-movie-feign
    # 设置sensitive-headers为空，说明Header需要在微服务之间透传
    # 列表：Cookie, Set-Cookie, Authorization
    sensitive-headers:
    path: /**
  servlet-path: /zuul

logging:
  level:
    com.netflix: INFO