server:
  port: 8050
spring:
  application:
    name: microservice-file-upload
  servlet:
    multipart:
      # 默认1M
      max-file-size: 2000Mb
      # 默认10M
      max-request-size: 2500Mb
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  prefer-ip-address: true
user:
  serviceUrl: http://127.0.0.1:8000/
logging:
  level:
    com.netflix: DEBUG