spring:
  application:
    name: microservice-discovery-eureka-ha
---
spring:
  # 指定profile=peer1
  profiles: peer1
server:
  port: 8761
eureka:
  instance:
    # 指定当profile=peer1时，主机名是peer1
    hostname: peer1
  client:
    serviceUrl:
      # 将自己注册到peer2这个Eureka上面去
      defaultZone: http://peer2:8762/eureka/
---
spring:
  # 指定profile=peer2
  profiles: peer2
server:
  port: 8762
eureka:
  instance:
    # 指定当profile=peer2时，主机名是peer2
    hostname: peer2
  client:
    serviceUrl:
      # 将自己注册到peer1这个Eureka上面去
      defaultZone: http://peer1:8761/eureka/
#java -jar ./target/microservice-discovery-eureka-ha-1.0-SNAPSHOT.jar --spring.profiles.active=peer1
#java -jar ./target/microservice-discovery-eureka-ha-1.0-SNAPSHOT.jar --spring.profiles.active=peer2