server:
  port: 8761
spring:
  application:
    name: microservice-discovery-eureka
  # Eureka安全验证未生效
  security:
    basic:
      enabled: true
    user:
      name: user
      password: password123
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
